[package]
name = "broccoli_salsa"
version = "0.1.0"
edition = "2018"
authors = ["nixenon"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
